version: "3.7"

services:
  simplequeuedev:
    build:
      context: $PWD/simplequeue
      dockerfile: $PWD/simplequeue/Dockerfile
      target: develop
    container_name: simplequeuedev
    working_dir: "/app/src/fabric"
    command: ["tail", "-f", "/dev/null"]
    environment:
      GO111MODULE: "on"
      docker: "true"
    volumes:
      - $PWD/simplequeue:/app
      - $PWD/Makefile:/app/src/fabric/Makefile
      - $PWD/scripts:/app/src/fabric/scripts
      - $PWD/.env.dist:/app/src/fabric/.env.dist
      - $PWD/.env:/app/src/fabric/.env

  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=orderer
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=orderer.block
      - ORDERER_GENERAL_LOCALMSPID=DEFAULT
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - $PWD/dev/msp:/etc/hyperledger/msp
      - $PWD/dev/orderer.block:/etc/hyperledger/fabric/orderer.block
    ports:
      - 7050:7050

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=test
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 5984:5984

  peer:
    container_name: peer
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=test
    volumes:
      - /var/run/:/host/var/run/
      - $PWD/dev/msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer
      - couchdb

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /opt/gopath/src/fabric
    command: "/bin/bash -c 'cd /opt/gopath/src/chaincodedev && ./script.sh'"
    volumes:
      - /var/run/:/host/var/run/
      - $PWD/dev/msp:/etc/hyperledger/msp
      - $PWD/dev/:/opt/gopath/src/chaincodedev/
      - $PWD/simplequeue/src/fabric:/opt/gopath/src/fabric/
    depends_on:
      - orderer
      - peer

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv
    tty: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=abstore
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /opt/gopath/src/fabric
    command: /bin/sh -c 'sleep 6000000'
    volumes:
      - /var/run/:/host/var/run/
      - $PWD/dev/msp:/etc/hyperledger/msp
      - $PWD/simplequeue/src/fabric:/opt/gopath/src/fabric/
    depends_on:
      - orderer
      - peer